import "@/styles/globals.scss";
import SearchComponent from '@/components/search/search.js'

export const metadata = {
  title: "Taiwan Travel Website ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className="min-h-full flex flex-col">
        <div>
          <div className="banner banner-section ">
            <div className="banner-section-mask"></div>
            <h1 className="banner-section-title">{metadata.title}</h1>
            <SearchComponent></SearchComponent>
          </div>
          <div className="flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
            <main className="flex flex-1 w-full max-w-5xl flex-col items-center justify-between mt-8 py-4 px-4 mb-2 bg-white dark:bg-black sm:items-start">
              {children}
            </main>
          </div>
        </div>
        <footer className="bg-gray-50">
          <div className="w-full mx-auto max-w-screen-xl p-4">
            <span className="block text-sm text-body text-center">© 2026  All Rights Reserved. © Product made by Joe Chen</span>
          </div>
      </footer>
      </body>
  
    </html>
  );
}
